2021-06-27 17:14:15.716271: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-06-27 17:14:17.546506: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-27 17:14:17.547466: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-06-27 17:14:17.555367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:25:00.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-06-27 17:14:17.555391: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-06-27 17:14:18.187103: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-06-27 17:14:18.187168: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-06-27 17:14:21.713272: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-06-27 17:14:24.018737: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-06-27 17:14:25.700862: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-06-27 17:14:26.563743: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-06-27 17:14:26.633250: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-06-27 17:14:26.638912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-27 17:14:26.639287: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-27 17:14:26.639369: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-27 17:14:26.640923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:25:00.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-06-27 17:14:26.640946: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-06-27 17:14:26.640958: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-06-27 17:14:26.640967: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-06-27 17:14:26.640976: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-06-27 17:14:26.640984: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-06-27 17:14:26.640993: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-06-27 17:14:26.641001: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-06-27 17:14:26.641009: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-06-27 17:14:26.643718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-27 17:14:26.646236: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-06-27 17:14:31.531738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-27 17:14:31.531782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-06-27 17:14:31.531788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-06-27 17:14:31.540790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13752 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:25:00.0, compute capability: 7.5)
WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
2021-06-27 17:14:31.611073: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 13.43G (14420966144 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.611850: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 12.09G (12978869248 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.612490: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 10.88G (11680982016 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.613122: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 9.79G (10512883712 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.613752: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 8.81G (9461595136 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.614384: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 7.93G (8515435520 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.615034: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 7.14G (7663891968 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.615711: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 6.42G (6897502720 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.616388: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 5.78G (6207752192 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.617068: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 5.20G (5586976768 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.617750: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 4.68G (5028278784 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.618389: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 4.21G (4525450752 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.619026: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 3.79G (4072905472 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.619662: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 3.41G (3665614848 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.620306: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 3.07G (3299053312 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.620998: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.76G (2969147904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.621691: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.49G (2672232960 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.622350: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.24G (2405009664 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.623008: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.02G (2164508672 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.623656: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.81G (1948057856 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.624284: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.63G (1753252096 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.624917: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.47G (1577926912 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.625553: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.32G (1420134144 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.626191: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.19G (1278120704 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.626844: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.07G (1150308608 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.627475: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 987.32M (1035277824 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:31.628130: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 888.59M (931750144 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-06-27 17:14:39.775138: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-27 17:14:39.778170: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2500000000 Hz
2021-06-27 17:14:41.754774: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-06-27 17:14:46.488957: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.491230: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.492703: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.494011: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.495900: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.497590: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.499024: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.501290: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.504387: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.556723: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.558977: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.561346: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.563634: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-27 17:14:46.598712: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-06-27 17:14:47.129578: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-06-27 17:14:47.131321: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-06-27 17:14:47.133146: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-06-27 17:14:47.134842: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "testing_script.py", line 66, in <module>
    batch_size=round(len(X_mmw_rD_train)/100), callbacks=[es, mc, csv_logger], verbose=1, shuffle=True)
  File "/work/hwei/HaowenWeiDeepLearning/IndexPenTrainingDir/IndexPen_Training/IndexPen_Training_venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/work/hwei/HaowenWeiDeepLearning/IndexPenTrainingDir/IndexPen_Training/IndexPen_Training_venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/work/hwei/HaowenWeiDeepLearning/IndexPenTrainingDir/IndexPen_Training/IndexPen_Training_venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/work/hwei/HaowenWeiDeepLearning/IndexPenTrainingDir/IndexPen_Training/IndexPen_Training_venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/work/hwei/HaowenWeiDeepLearning/IndexPenTrainingDir/IndexPen_Training/IndexPen_Training_venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/work/hwei/HaowenWeiDeepLearning/IndexPenTrainingDir/IndexPen_Training/IndexPen_Training_venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/work/hwei/HaowenWeiDeepLearning/IndexPenTrainingDir/IndexPen_Training/IndexPen_Training_venv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model/time_distributed_6/conv2d_1/Conv2D (defined at testing_script.py:66) ]] [Op:__inference_train_function_3866]

Function call stack:
train_function

